swagger: '2.0'
info:
  title: ArgentBank API documentation phase 2
  description: Contains all available API endpoints for the transactions part of the application
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    get:
      security: 
        - Bearer: []
      tags:
        - User Module
      summary: Get user accounts
      description: Retrieves the accounts of the logged in user
      parameters:
        - in: header
          name: Authorization
          description: Bearer token required to access this information
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Accounts retrieved successfully
          schema:
            $ref: "#/definitions/AccountsResponse"
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error

  /user/account/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get user transactions
      description: Retrieves transactions for a specific account
      parameters:
        - in: path
          name: accountId
          type: integer
          required: true
          description: ID of the specific account
        - in: header
          name: Authorization
          description: Bearer token required to access this information
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: "#/definitions/AccountTransactionsResponse"
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error

  /user/account/{accountId}/transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Get specific transaction
      description: Retrieves one specific transaction
      parameters:
        - in: path
          name: accountId
          type: integer
          required: true
          description: ID of the specific account
        - in: path
          name: transactionId
          type: integer
          required: true
          description: ID of the specific transaction
        - in: header
          name: Authorization
          description: Bearer token required to access this information
          type: string
          required: true
        - in: query
          name: month
          description: Month (YYYY-MM) to filter transactions
          type: string
          format: date
          required: true
      produces:
       - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error

    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Add transaction detail
      description: Adds a detail to a specific transaction
      parameters:
        - in: path
          name: accountId
          type: integer
          required: true
          description: ID of the specific account
        - in: path
          name: transactionId
          type: integer
          required: true
          description: ID of the specific transaction
        - in: header
          name: Authorization
          description: Bearer token required to access this information
          type: string
          required: true
        - in: body
          name: body
          description: Details to add to the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionDetail'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction detail added successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        '400':
          description: Invalid values
        '500':
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update transaction detail
      description: Updates details of a specific transaction
      parameters:
        - in: path
          name: accountId
          type: integer
          required: true
          description: ID of the specific account
        - in: path
          name: transactionId
          type: integer
          required: true
          description: ID of the specific transaction
        - in: header
          name: Authorization
          description: Bearer token required to access this information
          type: string
          required: true
        - in: body
          name: body
          description: Updated details for the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionDetail'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details updated successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        '400':
          description: Invalid fields
        '500':
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete transaction detail
      description: Deletes details of a specific transaction
      parameters:
        - in: path
          name: accountId
          type: integer
          required: true
          description: ID of the specific account
        - in: path
          name: transactionId
          type: integer
          required: true
          description: ID of the specific transaction
        - in: header
          name: Authorization
          description: Bearer token required to access this information
          type: string
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details deleted successfully
          schema:
            $ref: "#/definitions/TransactionResponse"
        '400':
          description: Invalid fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  AccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      accounts:
        type: array
        items:
          $ref: '#/definitions/Account'
  Account:
    type: object
    properties:
      id:
        type: integer
      balance:
        type: number
      type:
        type: string
  AccountTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      transactions:
        type: array
        items:
          $ref: '#/definitions/Transaction'
  Transaction:
    type: object
    properties:
      id:
        type: integer
      date:
        type: string
        pattern: "DD/MM/YY"
      amount:
        type: number
      type:
        type: string
      category:
        type: string
      notes:
        type: string
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      transaction:
        $ref: '#/definitions/Transaction'
  TransactionDetail:
    type: object
    properties:
      detail:
        type: string
        description: Specific detail related to the transaction
