export const GET_TOKEN = 'LOAD_TOKEN'
export const GET_TOKEN_SUCCESS = 'LOAD_TOKEN_SUCCESS'
export const GET_TOKEN_ERROR = 'LOAD_TOKEN_ERROR'

export const GET_USER = 'LOAD_GET_USER'
export const GET_USER_SUCCESS = 'LOAD_GET_USER_SUCCESS'
export const GET_USER_ERROR = 'LOAD_GET_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT'

export const EDIT_USER = 'LOAD_EDIT_USER'
export const EDIT_USER_SUCCESS = 'LOAD_EDIT_USER_SUCCESS'
export const EDIT_USER_ERROR = 'LOAD_EDIT_USER_ERROR'